const api = [
    {   
        'id': 0,
        "title" : "Java Script Basics",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 39.99,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        'id': 1,
        "title" : "Build Backend with Python",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 23.90,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },  
    {   
        'id': 2,
        "title" : "Web Development",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 38.30,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   'id': 3,
        "title" : "Build Websites With Redux",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 22.50,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   'id': 4,
        "title" : "Learning React.js",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 30.99,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   'id': 5,
        "title" : "JavaScripts Basics",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 45.80,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   'id': 6,
        "title" : "Mastering C++",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 20.52,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   'id': 7,
        "title" : "Deep learning",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 23.3,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   
        'id': 8,
        "title" :  "AL Basics",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 26.99,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   
        'id': 9,
        "title" : "Learning full stack with Mogngodb",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 38.30,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   
        'id': 10,
        "title" : "Django 3",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 32.00,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {   
        'id': 11,
        "title" : "Python and Django 3",
        "Author" : " Jon Ambrghe",
        "imageUrl": 'https://www.packtpub.com/media/catalog/product/cache/abd628df6af33f734d56624223a191f5/b/0/b05781_cover.png',
        "price": 22.00,
        "content": " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },

]
export default api;